//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for Entity Framework model.
// Code is generated on: 4/15/2020 1:45:00 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Data.Entity.Core.Objects;
using System.Data.Entity;
using RAMSDB.Interface;

namespace RAMSDB.Data
{
    public partial class EntityFrameworkUnitOfWorkFactory : IUnitOfWorkFactory
    {
        protected DbContext context = null;

        public EntityFrameworkUnitOfWorkFactory()
            : this(new RAMSDBModel.RAMSDBEntities())
        {
        }

        public EntityFrameworkUnitOfWorkFactory(DbContext context)
        {
            if (context == null)
            {
                throw new ArgumentNullException("dataContext");
            }
            this.context = context;
        }

        #region IUnitOfWorkFactory Members

        public virtual IUnitOfWork Create()
        {
            if (context == null)
                throw new InvalidOperationException("Context has not been initialized.");
            return new EntityFrameworkUnitOfWork(context);
        }
        #endregion
    }
}
