using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Entity;

namespace RAMSDB_WinForms
{
    public partial class TestForm : Form
    {
        public TestForm()
        {
            InitializeComponent();

            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            RAMSDBModel.RAMSDBEntities dbContext = new RAMSDBModel.RAMSDBEntities();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.UnpavedRoadConditionSurvey.LoadAsync().ContinueWith(loadTask =>
            {
    // Bind data to control when loading complete
    unpavedRoadConditionSurveyBindingSource.DataSource = dbContext.UnpavedRoadConditionSurvey.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }
    }
}
