//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Entity Framework DbContext template.
// Code is generated on: 4/15/2020 1:44:59 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Collections.ObjectModel;
using System.ComponentModel;

namespace RAMSDBModel
{
    [System.ComponentModel.DataAnnotations.Schema.Table("PrioritizedRoads", Schema = "dbo")]
    public partial class PrioritizedRoads : INotifyPropertyChanged
    {

        public PrioritizedRoads()
        {
            OnCreated();
        }

        #region Properties

        [System.ComponentModel.DataAnnotations.Key]
        [System.ComponentModel.DataAnnotations.Required]
        [System.ComponentModel.DataAnnotations.Schema.Column(TypeName = "int", Order = 0)]
        [System.ComponentModel.DataAnnotations.Schema.DatabaseGenerated(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity)]
        public virtual int PID
        {
            get
            {
                return _PID;
            }
            set
            {
                if (_PID != value)
                {
                    _PID = value;
                    OnPropertyChanged("PID");
                }
            }
        }
        private int _PID;

        [System.ComponentModel.DataAnnotations.Required]
        [System.ComponentModel.DataAnnotations.Schema.Column(TypeName = "smallint", Order = 1)]
        public virtual short Year
        {
            get
            {
                return _Year;
            }
            set
            {
                if (_Year != value)
                {
                    _Year = value;
                    OnPropertyChanged("Year");
                }
            }
        }
        private short _Year;

        [System.ComponentModel.DataAnnotations.Required]
        [System.ComponentModel.DataAnnotations.Schema.Column(TypeName = "int", Order = 2)]
        public virtual int AdminID
        {
            get
            {
                return _AdminID;
            }
            set
            {
                if (_AdminID != value)
                {
                    _AdminID = value;
                    OnPropertyChanged("AdminID");
                }
            }
        }
        private int _AdminID;

        [System.ComponentModel.DataAnnotations.Required]
        [System.ComponentModel.DataAnnotations.Schema.Column(TypeName = "int", Order = 3)]
        public virtual int RoadID
        {
            get
            {
                return _RoadID;
            }
            set
            {
                if (_RoadID != value)
                {
                    _RoadID = value;
                    OnPropertyChanged("RoadID");
                }
            }
        }
        private int _RoadID;

        [System.ComponentModel.DataAnnotations.Required]
        [System.ComponentModel.DataAnnotations.Schema.Column(TypeName = "bit", Order = 4)]
        public virtual bool PTentative
        {
            get
            {
                return _PTentative;
            }
            set
            {
                if (_PTentative != value)
                {
                    _PTentative = value;
                    OnPropertyChanged("PTentative");
                }
            }
        }
        private bool _PTentative;

        [System.ComponentModel.DataAnnotations.Schema.Column(TypeName = "bit", Order = 5)]
        public virtual bool? PFinal
        {
            get
            {
                return _PFinal;
            }
            set
            {
                if (_PFinal != value)
                {
                    _PFinal = value;
                    OnPropertyChanged("PFinal");
                }
            }
        }
        private bool? _PFinal;

        #endregion

        #region Navigation Properties
        [System.ComponentModel.DataAnnotations.Schema.ForeignKey("AdminID")]
        [System.ComponentModel.DataAnnotations.Schema.InverseProperty("PrioritizedRoads")]
        public virtual AdminBoundary AdminBoundary
        {
            get
            {
                return _AdminBoundary;
            }
            set
            {
                if (_AdminBoundary != value)
                {
                    _AdminBoundary = value;
                    OnPropertyChanged("AdminBoundary");
                }
            }
        }
        private AdminBoundary _AdminBoundary;
        [System.ComponentModel.DataAnnotations.Schema.ForeignKey("RoadID")]
        [System.ComponentModel.DataAnnotations.Schema.InverseProperty("PrioritizedRoads")]
        public virtual RoadsGISData RoadsGISData
        {
            get
            {
                return _RoadsGISData;
            }
            set
            {
                if (_RoadsGISData != value)
                {
                    _RoadsGISData = value;
                    OnPropertyChanged("RoadsGISData");
                }
            }
        }
        private RoadsGISData _RoadsGISData;

        #endregion

        #region Extensibility Method Definitions
        partial void OnCreated();
        #endregion

        #region INotifyPropertyChanged Members

        public event PropertyChangedEventHandler PropertyChanged;

        protected void OnPropertyChanged(string propertyName) {

          if (PropertyChanged != null)
            PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
        }

        #endregion
    }

}
