//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Entity Framework DbContext template.
// Code is generated on: 4/15/2020 1:44:59 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Collections.ObjectModel;
using System.ComponentModel;

namespace RAMSDBModel
{
    [System.ComponentModel.DataAnnotations.Schema.Table("RoadClassification", Schema = "dbo")]
    public partial class RoadClassification : INotifyPropertyChanged
    {

        public RoadClassification()
        {
            this.RoadsGISDatas = new ObservableListSource<RoadsGISData>();
            OnCreated();
        }

        #region Properties

        [System.ComponentModel.DataAnnotations.Key]
        [System.ComponentModel.DataAnnotations.Required]
        [System.ComponentModel.DataAnnotations.Schema.Column(TypeName = "int", Order = 0)]
        [System.ComponentModel.DataAnnotations.Schema.DatabaseGenerated(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity)]
        public virtual int RoadClassID
        {
            get
            {
                return _RoadClassID;
            }
            set
            {
                if (_RoadClassID != value)
                {
                    _RoadClassID = value;
                    OnPropertyChanged("RoadClassID");
                }
            }
        }
        private int _RoadClassID;

        [System.ComponentModel.DataAnnotations.Required]
        [System.ComponentModel.DataAnnotations.Schema.Column(TypeName = "nvarchar", Order = 1)]
        public virtual string RoadClassificationDescription
        {
            get
            {
                return _RoadClassificationDescription;
            }
            set
            {
                if (_RoadClassificationDescription != value)
                {
                    _RoadClassificationDescription = value;
                    OnPropertyChanged("RoadClassificationDescription");
                }
            }
        }
        private string _RoadClassificationDescription;

        [System.ComponentModel.DataAnnotations.Schema.Column(TypeName = "numeric", Order = 2)]
        public virtual decimal? CategoryMaxPoint
        {
            get
            {
                return _CategoryMaxPoint;
            }
            set
            {
                if (_CategoryMaxPoint != value)
                {
                    _CategoryMaxPoint = value;
                    OnPropertyChanged("CategoryMaxPoint");
                }
            }
        }
        private decimal? _CategoryMaxPoint;

        [System.ComponentModel.DataAnnotations.Required]
        [System.ComponentModel.DataAnnotations.Schema.Column(TypeName = "int", Order = 3)]
        public virtual int CriteriaWeightID
        {
            get
            {
                return _CriteriaWeightID;
            }
            set
            {
                if (_CriteriaWeightID != value)
                {
                    _CriteriaWeightID = value;
                    OnPropertyChanged("CriteriaWeightID");
                }
            }
        }
        private int _CriteriaWeightID;

        #endregion

        #region Navigation Properties
        [System.ComponentModel.DataAnnotations.Schema.ForeignKey("CriteriaWeightID")]
        [System.ComponentModel.DataAnnotations.Schema.InverseProperty("RoadClassifications")]
        public virtual CriteriaWeight CriteriaWeight
        {
            get
            {
                return _CriteriaWeight;
            }
            set
            {
                if (_CriteriaWeight != value)
                {
                    _CriteriaWeight = value;
                    OnPropertyChanged("CriteriaWeight");
                }
            }
        }
        private CriteriaWeight _CriteriaWeight;
        [System.ComponentModel.DataAnnotations.Schema.InverseProperty("RoadClassification")]
        public virtual ObservableListSource<RoadsGISData> RoadsGISDatas
        {
            get;
            set;
        }

        #endregion

        #region Extensibility Method Definitions
        partial void OnCreated();
        #endregion

        #region INotifyPropertyChanged Members

        public event PropertyChangedEventHandler PropertyChanged;

        protected void OnPropertyChanged(string propertyName) {

          if (PropertyChanged != null)
            PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
        }

        #endregion
    }

}
