//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Entity Framework DbContext template.
// Code is generated on: 4/15/2020 1:44:59 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Collections.ObjectModel;
using System.ComponentModel;

namespace RAMSDBModel
{
    [System.ComponentModel.DataAnnotations.Schema.Table("TradingCentersAlongRoad", Schema = "dbo")]
    public partial class TradingCentersAlongRoad : INotifyPropertyChanged
    {

        public TradingCentersAlongRoad()
        {
            this.MultiCriteriaAnalysisDatas = new ObservableListSource<MultiCriteriaAnalysisData>();
            OnCreated();
        }

        #region Properties

        [System.ComponentModel.DataAnnotations.Key]
        [System.ComponentModel.DataAnnotations.Required]
        [System.ComponentModel.DataAnnotations.Schema.Column(TypeName = "int", Order = 0)]
        [System.ComponentModel.DataAnnotations.Schema.DatabaseGenerated(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity)]
        public virtual int TradingCenterAlongRoadID
        {
            get
            {
                return _TradingCenterAlongRoadID;
            }
            set
            {
                if (_TradingCenterAlongRoadID != value)
                {
                    _TradingCenterAlongRoadID = value;
                    OnPropertyChanged("TradingCenterAlongRoadID");
                }
            }
        }
        private int _TradingCenterAlongRoadID;

        [System.ComponentModel.DataAnnotations.Schema.Column(TypeName = "varchar", Order = 1)]
        public virtual string TradingCenterAlongCategory
        {
            get
            {
                return _TradingCenterAlongCategory;
            }
            set
            {
                if (_TradingCenterAlongCategory != value)
                {
                    _TradingCenterAlongCategory = value;
                    OnPropertyChanged("TradingCenterAlongCategory");
                }
            }
        }
        private string _TradingCenterAlongCategory;

        [System.ComponentModel.DataAnnotations.Schema.Column(TypeName = "numeric", Order = 2)]
        public virtual decimal? CateogryMaxPoints
        {
            get
            {
                return _CateogryMaxPoints;
            }
            set
            {
                if (_CateogryMaxPoints != value)
                {
                    _CateogryMaxPoints = value;
                    OnPropertyChanged("CateogryMaxPoints");
                }
            }
        }
        private decimal? _CateogryMaxPoints;

        [System.ComponentModel.DataAnnotations.Required]
        [System.ComponentModel.DataAnnotations.Schema.Column(TypeName = "int", Order = 3)]
        public virtual int CriteriaWeightID
        {
            get
            {
                return _CriteriaWeightID;
            }
            set
            {
                if (_CriteriaWeightID != value)
                {
                    _CriteriaWeightID = value;
                    OnPropertyChanged("CriteriaWeightID");
                }
            }
        }
        private int _CriteriaWeightID;

        #endregion

        #region Navigation Properties
        [System.ComponentModel.DataAnnotations.Schema.InverseProperty("TradingCentersAlongRoad")]
        public virtual ObservableListSource<MultiCriteriaAnalysisData> MultiCriteriaAnalysisDatas
        {
            get;
            set;
        }
        [System.ComponentModel.DataAnnotations.Schema.ForeignKey("CriteriaWeightID")]
        [System.ComponentModel.DataAnnotations.Schema.InverseProperty("TradingCentersAlongRoads")]
        public virtual CriteriaWeight CriteriaWeight
        {
            get
            {
                return _CriteriaWeight;
            }
            set
            {
                if (_CriteriaWeight != value)
                {
                    _CriteriaWeight = value;
                    OnPropertyChanged("CriteriaWeight");
                }
            }
        }
        private CriteriaWeight _CriteriaWeight;

        #endregion

        #region Extensibility Method Definitions
        partial void OnCreated();
        #endregion

        #region INotifyPropertyChanged Members

        public event PropertyChangedEventHandler PropertyChanged;

        protected void OnPropertyChanged(string propertyName) {

          if (PropertyChanged != null)
            PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
        }

        #endregion
    }

}
