//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Entity Framework DbContext template.
// Code is generated on: 4/15/2020 1:44:59 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Collections.ObjectModel;
using System.ComponentModel;

namespace RAMSDBModel
{
    [System.ComponentModel.DataAnnotations.Schema.Table("TrafficCountHour", Schema = "dbo")]
    public partial class TrafficCountHour : INotifyPropertyChanged
    {

        public TrafficCountHour()
        {
            this.TrafficSurveys = new ObservableListSource<TrafficSurvey>();
            OnCreated();
        }

        #region Properties

        [System.ComponentModel.DataAnnotations.Key]
        [System.ComponentModel.DataAnnotations.Required]
        [System.ComponentModel.DataAnnotations.Schema.Column(TypeName = "int", Order = 0)]
        [System.ComponentModel.DataAnnotations.Schema.DatabaseGenerated(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity)]
        public virtual int TCHourID
        {
            get
            {
                return _TCHourID;
            }
            set
            {
                if (_TCHourID != value)
                {
                    _TCHourID = value;
                    OnPropertyChanged("TCHourID");
                }
            }
        }
        private int _TCHourID;

        [System.ComponentModel.DataAnnotations.Required]
        [System.ComponentModel.DataAnnotations.Schema.Column(TypeName = "varchar", Order = 1)]
        public virtual string HourFromTo
        {
            get
            {
                return _HourFromTo;
            }
            set
            {
                if (_HourFromTo != value)
                {
                    _HourFromTo = value;
                    OnPropertyChanged("HourFromTo");
                }
            }
        }
        private string _HourFromTo;

        #endregion

        #region Navigation Properties
        [System.ComponentModel.DataAnnotations.Schema.InverseProperty("TrafficCountHour")]
        public virtual ObservableListSource<TrafficSurvey> TrafficSurveys
        {
            get;
            set;
        }

        #endregion

        #region Extensibility Method Definitions
        partial void OnCreated();
        #endregion

        #region INotifyPropertyChanged Members

        public event PropertyChangedEventHandler PropertyChanged;

        protected void OnPropertyChanged(string propertyName) {

          if (PropertyChanged != null)
            PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
        }

        #endregion
    }

}
